### ISSUE TITLE
Boostrap node doesn't get 50 contacts

### ISSUE THREAD

**Issue by alebor-5** [alebor-5/D7024E#48]
Boostrap node doesn't get 50 contacts

**Comment by dejohansson** [comment]
This doesn't seem to be an issue. The reason for the missing contacts is that their respective buckets are full when they are added. When changing the bucket size to 50 all 49 nodes are added to the bootstrap routing table. https://github.com/alebor-5/D7024E/blob/aafe33b5db7862afb020b27c9e07e48a4c0ef93a/src/kademlia/routingtable.go#L9

This is not an issue but an intended feature.
I suggest we close this issue.

**Comment by alebor-5** [comment]
> 
> 
> This doesn't seem to be an issue. The reason for the missing contacts is that their respective buckets are full when they are added. When changing the bucket size to 50 all 49 nodes are added to the bootstrap routing table.
> 
> https://github.com/alebor-5/D7024E/blob/aafe33b5db7862afb020b27c9e07e48a4c0ef93a/src/kademlia/routingtable.go#L9
> 
> This is not an issue but an intended ✨_feature_✨.
> I suggest we close this issue.

Closed
