### ISSUE TITLE
Routing table eviction

### ISSUE THREAD

**Issue by dejohansson** [alebor-5/D7024E#49]
If a bucket is full when trying to add a new contact it should not be discarded right away. Instead it should check if some of the current contacts in the bucket are unresponsive, if that's the case the unresponsive contact should be evicted and the new contact inserted.
https://github.com/alebor-5/D7024E/blob/aafe33b5db7862afb020b27c9e07e48a4c0ef93a/src/kademlia/bucket.go#L32-L38

Does this requirement meet the Kademlia spec?
Any thoughts on how to implement this?

**Comment by alebor-5** [comment]
I'm on it 🐱‍🐉
